---
- include: yum.yml
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- include: install-supervisor-centos6.yml
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']
        and ansible_distribution_major_version == '6'

- include: install-supervisor-centos7.yml
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']
        and ansible_distribution_major_version == '7'

- include: user.yml

- include: thumbor.yml
