---
- include: yum.yml
  when: ansible_os_family == 'RedHat'

- include: virtualenv.yml
  when: ansible_os_family == 'RedHat'

- include: install-supervisor-centos6.yml
  when: ansible_os_family == 'RedHat'
        and ansible_distribution_major_version == '6'

- include: install-supervisor-centos7.yml
  when: ansible_os_family == 'RedHat'
        and ansible_distribution_major_version == '7'

- include: user.yml

- include: thumbor.yml
