---
- name: install nginx repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo
        owner=root group=root mode=0644
  tags: nginx

- name: install nginx
  yum: name=nginx
  tags: nginx

- name: mkdir /var/cache/nginx/cache
  file: path=/var/cache/nginx/cache state=directory
        owner=nginx group=nginx mode=0755
  tags: nginx

- name: copy nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
            owner=root group=root mode=0644
  tags: nginx
  notify: reload nginx

- name: copy default.conf
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
            owner=root group=root mode=0644
  tags: nginx
  notify: reload nginx
